### ISSUE TITLE
部署后在mechinfo服务器mechinfo_html文件夹下pull，会出现ahead of origin的情况。

### ISSUE THREAD

**Issue by kpaonaut** [DME-info/mechinfoBlog#11]
如题。目前的解决方案是再push一下上去就行了，似乎也没有什么问题。总之只要不影响mechinfoBlog这个repo就可以。但是很奇怪，心塞。谁解决了在下面回复，然后把这个issue关闭。

**Comment by qzlinqian** [comment]
啊竟然鸽了这么久。好像Aray的本意是deploy之后是public下的东西会传到mechinfo_html的repo，但是后来不知是不是我们没有理解个中奥义，最后实际上是整个mechinfoBlog被上传到了这个repo，于是必有冲突，这也是我早前push并在服务器pull了之后mechinfo没有变化的原因。然后在github上和服务器上好像分别会自动merge，于是服务器上会有ahead，push了之后会存在一段时间的“merge…”的commit信息，之后会自己消失。
不知道是不是这样解释。
